openapi: 3.0.1
info:
  title: Service
  version: 0.0.1
servers:
  - url: http://localhost:8081
paths:
  /demo:
    post:
      summary: Summary
      operationId: demo
#      parameters:
#        - in: header
#          name: Accept-Version
#          description: Version of the API to use
#          schema:
#            type: integer
#          required: true
      requestBody:
        description: Demo Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemoRequest'
      responses:
        200:
          description: description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DemoResponse"

components:
  schemas:
    DemoRequest:
      type: object
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/id'
        name:
          type: string
          maxLength: 255
    DemoResponse:
      type: object
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/id'
        name:
          type: string
          maxLength: 255
    id:
      type: string
      maxLength: 255
