openapi: 3.0.1
info:
  title: Rest Service
  version: 0.0.0
servers:
  - url: http://localhost:8091
paths:
  /demo:
    post:
      summary: Demo Service
      operationId: demo
      parameters:
#        - in: header
#          name: Accept-Version
#          description: Version of the API to use
#          schema:
#            type: integer
#          required: true
      requestBody:
        description: Demo Request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemoRequest'
      responses:
        200:
          description: Do it
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DemoResponse"
#        400:
#          description: Ooops.
#          content:
#            application/json:
#              schema:
#                $ref: "#/components/schemas/ServiceError"
#        500:
#          description: Ooops.
#          content:
#            application/json:
#              schema:
#                $ref: "#/components/schemas/ServiceError"

components:
  schemas:
    DemoRequest:
      type: object
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          $ref: '#/components/schemas/Name'
    DemoResponse:
      type: object
      required:
        - id
        - name
      properties:
        id:
          $ref: '#/components/schemas/Id'
        name:
          $ref: '#/components/schemas/Name'
#    ServiceError:
#      type: object
#      required:
#        - requestId
#      properties:
#        id:
#          $ref: '#/components/schemas/Id'
#        code:
#          type: string
#          maxLength: 255
#        subcode:
#          type: string
#          maxLength: 255
#        reason:
#          type: string
    Id:
      type: integer
    Name:
      type: string
      maxLength: 255