spring.profiles.active: local
server:
  port: 8092
  ssl:
    enabled: false # Uses self-signed certificate because no key-store configuration is specified.

service:
  address: http://localhost:8091/demo