#spring.profiles.active: local
server:
  port: 9091
  ssl:
    enabled: false # Uses self-signed certificate because no key-store configuration is specified.
    client-auth:

service:
  address: http://localhost:8092/service/demo

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    au.com.mebank.client: DEBUG
    au.com.mebank.client.handler: DEBUG

spring:
  banner:
    image:
      location: "classpath:/logo.png"
      height: 25
      width: 40

management:
  endpoint:
    prometheus:
      enabled: on
    health:
      show-details: 'always'
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
      path-mapping:
        health: healthz
        prometheus: metrics
  server:
    port: 9083

#    prometheus:
#      enabled: true

#    include: 'info,health,prometheus'

